function [ mean_sum_error ] = sumError (n)
% SUMERROR Sums n random numbers generated by rand , in two different
% orders , and calculates the difference to estimate the error in the sum.
% Averages such errors for numTrial=100 cases to get a general estimate of
% the error in the sum of n numbers of similar values .
%
%   Input:
%   n: Desired length of vector to be summed up
%
%   Output:
%   mean_sum_error: Mean of estimated round-off error arising from 
%   summation over num_trials

num_trial = 100; %Number of trials
sum_error = 0; %Initialization of error

for k=1:num_trial
    
    vec = rand(1,n); %In each iteration, create a vector having normally distributed elements
    sum_error = sum_error + sumDiff(vec); %Calculate errors and accumulate in sum_error
    
end

mean_sum_error = sum_error / num_trial; %Calculate mean of errors

end